create table netology.CUSTOMERS
(
    id int generated by default as identity primary key,
    name varchar not null,
    surname varchar not null,
    age int     not null,
    phone_number varchar not null
);

insert into netology.CUSTOMERS (name, surname, age, phone_number)
values ('SHOM', 'KED', 22, '+79001112222');

insert into netology.CUSTOMERS (name, surname, age, phone_number)
values ('DAR', 'LOGIS', 50, '+79004445556');

insert into netology.CUSTOMERS (name, surname, age, phone_number)
values ('METUY', 'KARI', 36, '+79007778889');